[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flatland"
version = "0.1.0"
authors = [
  { name="systemshift", email="." },
]
description = "A Minimalist, Constraint-Driven 2D Framework for Testing LLM-Generated Environments"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.21.0",
    "openai>=1.0.0",
]

[project.urls]
"Homepage" = "https://github.com/systemshift/flatland"
"Bug Tracker" = "https://github.com/systemshift/flatland/issues"
