version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - FLATLAND_OPENAI_KEY=${OPENAI_API_KEY}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    
  # Frontend web service
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped